@echo off
echo Starting backend with elevated permissions...
cd /d "c:\Users\Gannu\OneDrive\Desktop\IDP_PROJECT\dotnet-api"
echo Building project...
dotnet build --configuration Release
echo Starting API server...
dotnet run --configuration Release --no-build
pause
